### PR TITLE
Add IDL for Echo::echo thrift crossdock behavior

### PR DESCRIPTION
**Pull request by kriskowal**
r @yarpc/yarpc

### CODE REVIEW

**Comment by breerly** [comment]
Perhaps just link to the file instead? Or if you want to inline it - remove the file.

**Comment by kriskowal** [comment]
Perhaps I can just add it to ThriftTest.

**Comment by kriskowal** [comment]
Oh, no, I already added Echo.thrift but forgot to link.

**Comment by breerly** [comment]
:+1:

**Pull request merged**
